<br /><br />
<div id="view-content">
	<p>Here is what has been created with the Zend_tool creating the Submit action for the Bug Controller</p><br /><br />
	<p>View script for controller <b>Bug</b> and script/action name <b>submit</b></p>
</div>

<h2>Submit a bug report</h2>
<p>To submit a new bug report please fill out this form completely:</p>
<?php
echo $this->form->render();
// echo $this->form; does the same thing 
?>