<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype ();
?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php
	echo $this->headTitle ();
	echo $this->headScript ();
	// add a link to the site style sheet
	// echo $this->headLink()->appendStylesheet('/css/layout.css');
	echo $this->loadSkin ( $this->skin );
	echo $this->headLink ();
	?>
</head>

<body>
	<div id="pageWrapper">
		<div id="header">
			<h1>Osmosys</h1>
		</div>
		<div id="nav">
			<?php echo $this->layout()->nav;?>&nbsp;
		</div>
		<div id="sidebar">
			<div id="subNav">
				<?php echo $this->layout()->subNav;?>&nbsp; 
			</div>
			<div id="adminMenu"> 
				<?php echo $this->layout()->adminMenu;?>&nbsp;
			</div>
			<div id="userForm">
				<?php echo $this->layout()->userForm;?>&nbsp; 
			</div>
			<p>#sidebar</p>
		</div>
		<div id="main"> 
			<?php echo $this->layout()->content;?>&nbsp;
		</div>
		<div id="footer">
			<p>
				<em>Powered by the Zend Framework</em>
			</p>
		</div>
	</div>
</body>
</html>