<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
//echo Zend_Version::getLatest();
$this->layout()->nav = $this->action('render', 'menu', null,
	array('menu' => $this->mainMenuId)); 
$this->layout()->adminMenu = $this->action(
	'render', 'menu', null, array('menu' => $this->adminMenuId) 
);
$this->layout()->userForm = $this->action('index', 'user'); 
$this->layout()->userThumbnail = $this->action('thumbnail', 'user');

?>
<!--[if lte IE 6]>

    <div class="ie6-message header">
      <span class="message-icon"></span>
      <h3>Warning</h3>
      <p>You are using Internet Explorer version 6.0 or lower.  Due to security issues and lack of support for Web Standards, it is highly recommended that you upgrade to a modern browser.</p>
      <div class="browsers"><p>Download:</p>
        <a href="http://www.mozilla.com/firefox"><img src="/sites/all/themes/schoology_theme/images/firefox.gif" alt="Download Firefox" /></a>
        <a href="http://www.google.com/chrome"><img src="/sites/all/themes/schoology_theme/images/chrome.gif" alt="Download Google Chrome" /></a>
        <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx"><img src="/sites/all/themes/schoology_theme/images/ie.gif" alt="Download Internet Explorer" /></a>
        <a href="http://www.apple.com/safari/"><img src="/sites/all/themes/schoology_theme/images/safari.gif" alt="Download Safari" /></a>
      </div>
    </div>

    <![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php 
	$this->loadSkin($this->skin); 
	echo $this->headTitle();
	echo $this->headScript(); 
	echo $this->headLink();
	?>
</head>

<body>

	<div id="lnwrap">
		<header id="main-header" class="container_16 clearfix">
	    	<h1 id="logo" class="grid_3 suffix_4"><a href='/'>Osmosys</a></h1>
	    	<nav id="main-nav" class="grid_7">
	    		<h1>Main page navigation</h1>
	    		<?php
					echo $this->layout()->nav; 
				?>&nbsp;
	    	</nav>
	    	<h1 id="thumbnail" class="grid_1 suffix_1">
<!-- 	    		<a id='imagespace'/> </a> -->
	    		<?php
					echo $this->layout()->userThumbnail; 
				?>
	    	</h1>
	    </header>
	</div><!-- logonavwrap -->
	<section id="content" class="container_16 clearfix">
		<div id="sidebar" class="grid_4"> 
			<div id="userForm"> 
				<?php
				echo $this->layout()->userForm;
				?>&nbsp; 
			</div>
			<div id='searchForm'>
				<h2><?php echo $this->translate('Search Site');?></h2>
				<?php 
				    $searchForm = new Form_SearchForm();
				    $searchForm->setAction('/search');
				    echo $searchForm->render();
				?>
				<br />
			</div>
<!-- 			<div id="subNav">  -->
			<?php
// 			echo $this->layout()->subNav;
			?>
<!-- 			</div> -->
			<div id="adminMenu"> 
			<?php
			echo $this->layout()->adminMenu;
			?>&nbsp; 
			</div>
		</div> <!-- SideBar -->
		<div id="main" class="grid_12" >
			<?php
			echo $this->layout()->content
			?>&nbsp; 
		</div><!-- Main -->
	</section><!-- Content Wrapper -->	
	
	<section id="footer" class="container_16 clearfix">
		<p><em>Powered by the Zend Framework</em></p> 
	</section>
	
<!-- </div> -->
</body>
</html>